version: '3.8'

services:
  laravel_ten_app:
    build:
      dockerfile: Dockerfile
    image: laravel_ten_app_image
    container_name: laravel_ten_app
    working_dir: /var/www
    networks:
      - laravel_ten_app_network
    volumes:
      - .:/var/www

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    ports:
      - 9090:80
    networks:
      - laravel_ten_app_network
    depends_on:
      - laravel_ten_app

networks:
  laravel_ten_app_network:
    driver: bridge
